/**
 * Article Type Definition
 * 
 * Represents an article/content item in the app.
 * This type is used throughout the app for type safety and consistency.
 * 
 * Database Mapping:
 * This type should match your Supabase 'articles' table schema.
 * If you change the database schema, update this type accordingly.
 */

/**
 * Represents a single article in the system.
 * 
 * @example
 * const article: Article = {
 *   id: '550e8400-e29b-41d4-a716-446655440000',
 *   title: 'Introduction to React Native',
 *   summary: 'Learn the basics of building mobile apps with React Native...',
 *   tags: ['react-native', 'mobile', 'javascript'],
 *   externalUrl: 'https://example.com/article/react-native-intro',
 *   createdAt: '2024-01-15T10:30:00.000Z',
 * };
 */
export interface Article {
  /**
   * Unique identifier for the article.
   * Typically a UUID from Supabase.
   */
  id: string;

  /**
   * The article's headline/title.
   * Should be concise and descriptive.
   */
  title: string;

  /**
   * A brief summary or excerpt of the article content.
   * Used for previews in lists/cards.
   */
  summary: string;

  /**
   * Array of tags/categories for the article.
   * Used for filtering and organization.
   * 
   * @example ['technology', 'ai', 'tutorial']
   */
  tags: string[];

  /**
   * URL to the full article content.
   * Can be an external link or internal resource.
   */
  externalUrl: string;

  /**
   * ISO 8601 timestamp of when the article was created.
   * 
   * @example '2024-01-15T10:30:00.000Z'
   */
  createdAt: string;
}

/**
 * Type for creating a new article (without id and createdAt).
 * These fields are auto-generated by the database.
 * 
 * @example
 * const newArticle: ArticleInsert = {
 *   title: 'My New Article',
 *   summary: 'This is a summary...',
 *   tags: ['news'],
 *   externalUrl: 'https://example.com/article',
 * };
 */
export type ArticleInsert = Omit<Article, 'id' | 'createdAt'>;

/**
 * Type for updating an article (all fields optional except id).
 * Only include fields you want to change.
 * 
 * @example
 * const update: ArticleUpdate = {
 *   id: '550e8400-e29b-41d4-a716-446655440000',
 *   title: 'Updated Title',
 * };
 */
export type ArticleUpdate = Pick<Article, 'id'> & Partial<ArticleInsert>;

/**
 * Type for article list items (could be a subset of Article for performance).
 * Currently the same as Article, but can be customized if needed.
 */
export type ArticleListItem = Article;
